name: CI

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Black (check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Prepare results directory
        run: |
          python - << 'PY'
          import os
          os.makedirs('test-results', exist_ok=True)
          PY

      - name: Set PYTHONPATH (Unix)
        if: runner.os != 'Windows'
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Set PYTHONPATH (Windows)
        if: runner.os == 'Windows'
        run: echo "PYTHONPATH=$env:PYTHONPATH;$(pwd)" >> $env:GITHUB_ENV

      - name: Debug working directory and files
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of tests directory:"
          ls -la tests/
          echo "Python path:"
          python -c "import sys; [print(p) for p in sys.path]"
          echo "Checking if app.py exists:"
          ls -la app.py
          echo "Checking if conftest.py exists:"
          ls -la conftest.py

      - name: Pytest (with JUnit XML and coverage)
        run: |
          python -m pytest -q \
            --junitxml=test-results/pytest.xml \
            --cov=. \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov-report=html \
            --cov-fail-under=70

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.os }}-py${{ matrix.python-version }}
          path: test-results/

      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.os }}-py${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.os }}-py${{ matrix.python-version }}
          path: htmlcov/
